const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const context=await browser.newContext({viewport:{width:390,height:844}});
  let price=95;
  const now=()=>Math.floor(Date.now()/1000),iso=t=>new Date(t*1000).toISOString();
  const q=()=>({symbol:'TEST/TRY',pair:'TESTTRY',price,bid:price,change:0,volume_try:100000,price_updated_at:iso(now()),price_source:'TEST'});
  const errors=[];
  await context.addInitScript(()=>{
    if(localStorage.getItem('test-fixture'))return;
    localStorage.setItem('test-fixture','1');
    const now=Math.floor(Date.now()/1000),iso=t=>new Date(t*1000).toISOString();
    const p={coin:{symbol:'TEST/TRY'},entry:100,amount:1000,quantity:10,fee:.001,slippage:.001,target:110,stop:90,openedAt:iso(now-7200),frames:['one_hour']};
    localStorage.setItem('coinpilot-pro-positions',JSON.stringify([{...p,id:'p1'},{...p,id:'p2'},{...p,id:'p3',sellOrder:{id:'old-order',status:'pending',price:110,createdAt:iso(now-3600),replay:true}}]));
    localStorage.setItem('coinpilot-pro-history','[]');
  });
  await context.route('**/api/**',async route=>{
    const u=new URL(route.request().url());let d={status:'success'};
    if(u.pathname==='/api/dashboard')d={...d,live:false,quotes:{'TEST/TRY':q()},gainers:[q()],losers:[q()]};
    else if(u.pathname==='/api/quote')d={...d,coin:q()};
    else if(u.pathname==='/api/radar')d={...d,items:[],scanning:false,scanned:0,total:0,errors:[]};
    else if(u.pathname==='/api/targets')d={...d,symbol:'TEST/TRY',frames:{fifteen_minute:{target:111},one_hour:{target:120},daily:{target:150}},errors:[],analyzed_at:iso(now())};
    else if(u.pathname==='/api/exit')return route.fulfill({status:503,json:{status:'error',message:'Testte sinyal yok'}});
    else if(u.pathname==='/api/price-path'){
      const t=Math.floor((now()-600)/60)*60,from=Number(u.searchParams.get('from'));
      d={...d,symbol:'TEST/TRY',candles:t>=from?[{time:t,high:115,low:94,volume:10}]:[],through:Math.floor(now()/60)*60,missing_minutes:10,clipped:false,has_more:false};
    }else return route.fulfill({status:503,json:{status:'error',message:'Testte kapalı'}});
    await route.fulfill({json:d});
  });
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:10001/');
  await page.waitForFunction(()=>state.history.some(x=>x.positionId==='p3'));
  assert.equal(await page.evaluate(()=>state.history.filter(x=>x.positionId==='p3').length),1);
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').tracking.targetHit.source),'minute');
  await page.evaluate(()=>{switchPage('positions');openSellOrder('p1');});
  await page.locator('#order-price').fill('300');
  await page.locator('#order-replay').check();
  await page.locator('#order-submit').click();
  await page.waitForFunction(()=>state.positions.find(p=>p.id==='p1').sellOrder?.price===300);
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').sellOrder.status),'pending');
  await page.reload();
  await page.waitForFunction(()=>state.positions.find(p=>p.id==='p1')?.sellOrder?.price===300);
  await page.evaluate(()=>switchPage('positions'));
  await page.screenshot({path:'test-output/positions-mobile.png',fullPage:true});
  await page.evaluate(()=>cancelSellOrder('p1'));
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').sellOrder.status),'cancelled');
  await page.evaluate(()=>openSellOrder('p2'));
  await page.locator('#order-price').fill('105');await page.locator('#order-size').fill('5');await page.locator('#order-submit').click();
  await page.waitForFunction(()=>state.positions.find(p=>p.id==='p2').sellOrder?.price===105);
  const second=await context.newPage();second.on('pageerror',e=>errors.push(e.message));
  await second.goto('http://127.0.0.1:10001/');
  await second.waitForFunction(()=>typeof loadDashboard==='function');
  price=106;await Promise.all([page.evaluate(()=>loadDashboard()),second.evaluate(()=>loadDashboard())]);
  await page.waitForFunction(()=>state.history.some(x=>x.positionId==='p2'));
  assert.equal(await page.evaluate(()=>state.history.find(x=>x.positionId==='p2').exit),105);
  await page.evaluate(()=>loadDashboard());
  assert.equal(await page.evaluate(()=>state.history.filter(x=>x.positionId==='p2').length),1);
  assert.equal(await second.evaluate(()=>JSON.parse(localStorage.getItem('coinpilot-pro-history')).filter(x=>x.positionId==='p2').length),1);
  await second.close();
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p2').quantity),5);
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p2').amount),500);
  await page.evaluate(()=>loadPositionTargets());
  await page.waitForFunction(()=>targetCache.get('TEST/TRY')?.data?.frames?.daily?.target===150);
  const staleBackup=await page.evaluate(()=>JSON.stringify({app:'CoinPilot TR',version:1,positions:state.positions,history:state.history,frames:state.frames,favorites:state.favorites}));
  await page.evaluate(()=>{switchPage('positions');closePosition('p1');});
  await page.locator('#partial-size').fill('101');await page.locator('#partial-submit').click();
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').quantity),10);
  await page.locator('[data-sale-percent="50"]').click();
  await page.locator('#partial-submit').scrollIntoViewIfNeeded();
  const partialBox=await page.locator('#partial-submit').boundingBox();assert.ok(partialBox.y+partialBox.height<=844);
  await page.screenshot({path:'test-output/partial-mobile.png'});
  await page.locator('#partial-submit').click();
  await page.waitForFunction(()=>state.positions.find(p=>p.id==='p1')?.quantity===5);
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').amount),500);
  assert.equal(await page.evaluate(()=>state.history.find(h=>h.positionId==='p1').closesPosition),false);
  await page.locator('#import-backup').setInputFiles({name:'old-backup.json',mimeType:'application/json',buffer:Buffer.from(staleBackup)});
  await page.waitForFunction(()=>document.getElementById('backup-message').textContent.includes('birleştirildi'));
  assert.equal(await page.evaluate(()=>state.positions.find(p=>p.id==='p1').quantity),5);
  await page.evaluate(()=>closePosition('p1'));await page.locator('[data-sale-percent="100"]').click();await page.locator('#partial-submit').click();
  await page.waitForFunction(()=>!state.positions.some(p=>p.id==='p1'));
  assert.equal(await page.evaluate(()=>state.history.filter(h=>h.positionId==='p1').length),2);
  assert.equal(await page.evaluate(()=>state.history.filter(h=>h.positionId==='p1').reduce((s,h)=>s+h.amount,0)),1000);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.evaluate(()=>{switchPage('positions');openSellOrder('p2');});
  await page.locator('#order-submit').scrollIntoViewIfNeeded();
  const box=await page.locator('#order-submit').boundingBox();assert.ok(box.y+box.height<=844);
  await page.screenshot({path:'test-output/order-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS: targets, manual half/full sale, partial limit, cost conservation, stale backup protection, two-tab idempotency, overnight evidence, mobile dialogs, zero JS errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
